# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build-Test-Deploy

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install -g gatsby-cli
    - run: npm install -g surge
    - run: gatsby build
    - name: upload public folder to artifacts
      uses: actions/upload-artifact@v2
      with:
        name: gatsby-public-folder
        path: ./public


  staging-test:
    runs-on: ubuntu-latest 
    name: staging 
    needs: build 
    steps: 
    - name: download public folder to artifacts
      uses: actions/download-artifact@v2
      with:
        name: gatsby-public-folder
        path: ./public    
    - name: Deploy to staging-orhankalayci.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'staging-orhankalayci.surge.sh'
        project: './public'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}

    - run: curl http://staging-orhankalayci.surge.sh >> test.file 
    - run: sleep 19
    - run: grep "Hello Orhan!" test.file



  deploy:
    runs-on: ubuntu-latest 
    name: deploy 
    needs: staging-test 
    steps: 
    - name: download public folder to artifacts
      uses: actions/download-artifact@v2
      with:
        name: gatsby-public-folder
        path: ./public    
    - name: Deploy to orhankalayci.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'orhankalayci.surge.sh'
        project: './public'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}

